In [1]:
# Импорт необходимых инструментов
from mnist import MNIST
import numpy as np
import matplotlib.pyplot as plt
import sys
mnist_data = MNIST('./MNIST_DATA')

In [ ]:
# np.set_printoptions(threshold=sys.maxsize)
# np.set_printoptions(threshold=10)

In [2]:
# Функция активации
def activate_function(current_value):
    if(current_value > 0):
        return 1
    else:
        return 0

In [59]:
# Скорость обучения
learning_speed = 0.5
# Cдвиг
learning_offset = np.random.rand(1, 10)
# Эпохи обучения
max_epochs = 20
print(learning_offset)

[[0.55494788 0.34999483 0.75163692 0.33902656 0.30116587 0.4991594
  0.46498192 0.65488976 0.68981238 0.05753065]]


In [60]:
images_train, labels_train = mnist_data.load_training()

learning_data = mnist_data.process_images_to_numpy(images_train)

correct_answers = mnist_data.process_labels(labels_train)

In [61]:
# Правильные ответы
y = correct_answers
# Нейроны
x = np.around(learning_data / 255)
x = np.hstack((x, np.ones((len(x), 1))))
# Обучающая выборка 60000 x 785
print(x)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [62]:
# Веса
w = np.random.rand(784, 10)
w = np.vstack((w, learning_offset))
# Веса на входы 785 x 10
print(w)

[[0.98885452 0.69760477 0.37784838 ... 0.45832037 0.12504232 0.45652165]
 [0.66593983 0.32847066 0.23312592 ... 0.87102261 0.10939902 0.57086833]
 [0.01965061 0.02163487 0.31202724 ... 0.5984408  0.51658908 0.14778613]
 ...
 [0.06302979 0.50300417 0.01935645 ... 0.76099789 0.16865232 0.87231306]
 [0.06180806 0.57295016 0.27057769 ... 0.8952017  0.97292018 0.25725943]
 [0.55494788 0.34999483 0.75163692 ... 0.65488976 0.68981238 0.05753065]]


In [63]:
temp = np.eye(10)
make_answer = np.vectorize(activate_function)

for epoch in range(max_epochs):

    for i in range(len(x)):
        # 1x10
        y_1 = x[i]@w
        y_1 = make_answer(y_1)
        ei = temp[y[i]] - y_1
        Di = learning_speed * np.dot(x[i].reshape((785, 1)), ei.reshape((1, 10)))
        w = w + Di

In [64]:
print(w)

# 60000x10
y_1 = x@w
y_1 = make_answer(y_1)
np.set_printoptions(threshold=sys.maxsize)

# Выходные значения
print(y_1)
np.set_printoptions(threshold=10)

[[ 9.88854518e-01  6.97604767e-01  3.77848379e-01 ...  4.58320370e-01
   1.25042324e-01  4.56521651e-01]
 [ 6.65939828e-01  3.28470665e-01  2.33125919e-01 ...  8.71022612e-01
   1.09399022e-01  5.70868329e-01]
 [ 1.96506150e-02  2.16348654e-02  3.12027240e-01 ...  5.98440805e-01
   5.16589083e-01  1.47786131e-01]
 ...
 [ 6.30297920e-02  5.03004173e-01  1.93564526e-02 ...  7.60997890e-01
   1.68652319e-01  8.72313064e-01]
 [ 6.18080568e-02  5.72950163e-01  2.70577686e-01 ...  8.95201701e-01
   9.72920184e-01  2.57259429e-01]
 [-6.34450521e+01 -2.15000517e+00 -3.02483631e+01 ... -6.34511024e+00
  -1.12810188e+02 -4.64424694e+01]]
[[0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0

In [65]:
images_test, labels_test = mnist_data.load_testing()

learning_data = mnist_data.process_images_to_numpy(images_test)

correct_answers = mnist_data.process_labels(labels_test)

In [66]:
y = correct_answers
x = np.around(learning_data / 255)
x = np.hstack((x, np.ones((len(x), 1))))
# Тестовая выборка 10000 x 785
print(x)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [67]:
y_1 = x@w
y_1 = make_answer(y_1)

In [68]:
def predict(vector):
    result = 0
    for i in range(10):
        if(vector[i] == 1): result = i
    return result

In [69]:
right = 0
for i in range(len(x)):
    if(predict(y_1[i]) == y[i]):
        right += 1

accyracy = right / 100

# Правильных ответов в %
print(accyracy)

74.95
